<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>14ad366b-74d9-4fa7-a9cd-65e4fe8d51c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div/div[2]/ul/li/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>仮想通貨</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;cmc-app-wrapper cmc-app-wrapper--env-prod cmc-theme--day sc-1mezg3x-0 igCEta&quot;]/div[@class=&quot;container cmc-main-section&quot;]/div[@class=&quot;cmc-main-section__content&quot;]/div[@class=&quot;cmc-homepage&quot;]/div[@class=&quot;cmc-table-listing cmc-table-listing--is-tab-selected vmm4qx-0 ggcuKT&quot;]/div[@class=&quot;cmc-table-listing__tabs-wrapper&quot;]/div[@class=&quot;cmc-cryptocurrency-listing-tabs sc-1u2p5e2-0 liMFmL cmc-tabs sc-80vbsl-0 dZnnPU&quot;]/ul[@class=&quot;cmc-tabs__header&quot;]/li[@class=&quot;cmc-tab__trigger cmc-tab__trigger--selected&quot;]/div[@class=&quot;cmc-popover sc-12d77vg-0 binXtg&quot;]/div[@class=&quot;cmc-popover__trigger&quot;]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div/div[2]/ul/li/div/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='すべて見る'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ランキング'])[2]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ウォッチリスト'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/span</value>
   </webElementXpaths>
</WebElementEntity>
